services:
  - type: web
    name: hostel-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hostel-db
          property: connectionString
      - key: RENDER
        value: "true"

  - type: pgsql
    name: hostel-db
    plan: free
    databaseName: hostel_management
    user: hostel_user
